name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "x64"
            docker-arch: "amd64"
          - arch: "arm64"
            docker-arch: "arm64"
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Build
        run: |
          # docker buildx build --platform=linux/${{ matrix.docker-arch }} --output type=local,dest=build .
          mkdir build && touch build/busybox.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}
          path: build/busybox.tar.gz
          retention-days: 5

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare artifacts
      run: |
        ls -l
        mv busybox/busybox/x64 busybox-x64-${{ steps.tag.outputs.new_tag }}.tar.gz
        mv busybox/busybox/arm64 busybox-arm64-${{ steps.tag.outputs.new_tag }}.tar.gz
    - name: Create and upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: busybox-x64-${{ steps.tag.outputs.new_tag }}.tar.gz,busybox-arm64-${{ steps.tag.outputs.new_tag }}.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
