name: Build
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "x64"
            docker-arch: "amd64"
          - arch: "arm64"
            docker-arch: "arm64"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and Publish
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_ARCH: ${{ matrix.docker-arch }}
          CLASSIFIER: ${{ matrix.arch }}