name: Build
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "x64"
            docker-arch: "amd64"
          - arch: "arm64"
            docker-arch: "arm64"
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Build
        run: docker buildx build --platform=linux/${{ matrix.docker-arch }} --output type=local,dest=build .